In [1]:
!pip install gymnasium

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 5.4 MB/s eta 0:00:00


In [2]:
import gymnasium as gym
import numpy as np
import time
from IPython import display

In [3]:
env = gym.make('FrozenLake-v1', render_mode="ansi")

In [4]:
env.P[0][3] # Transition model

/usr/local/lib/python3.10/dist-packages/gymnasium/core.py:311: UserWarning: WARN: env.P to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.P` for environment variables or `env.get_wrapper_attr('P')` that will search the reminding wrappers.
  logger.warn(


[(0.3333333333333333, 1, 0.0, False),
 (0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 0, 0.0, False)]

In [5]:
env.observation_space.n

16

In [6]:
env.action_space.n

4

In [7]:
def play(env, policy, render=False):
    state, _ = env.reset()
    total_reward = 0
    steps = 0
    done = False
    while not done:
        action = policy[state]
        next_state, reward, done, info, _ = env.step(action)
        total_reward += reward
        steps += 1
        if render:
            print(env.render())
            time.sleep(0.5)
            if not done:
                display.clear_output(wait=True)
        state = next_state

    return (total_reward, steps)

In [8]:
policy_0 = np.asarray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
play(env, policy_0)

(0.0, 7)

In [9]:

policy_0 = np.asarray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
play(env, policy_0, True)


  (Left)
SFFF
FHFH
FFFH
HFFG



(0.0, 3)

In [10]:
policy_1 = np.asarray([0, 1, 1, 3, 1, 0, 2, 0, 1, 1, 2, 2, 3, 3, 1, 0])
play(env, policy_1, True)

  (Up)
SFFF
FHFH
FFFH
HFFG



(0.0, 6)

In [11]:
policy_2 = np.array([1, 1, 1, 3, 0, 1, 2, 3, 1, 1, 2, 3, 2, 2, 1, 3])
play(env, policy_2, True)

  (Down)
SFFF
FHFH
FFFH
HFFG



(0.0, 11)

In [12]:
policy_3 = np.array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0])
play(env, policy_3, True)

  (Left)
SFFF
FHFH
FFFH
HFFG



(0.0, 32)

In [13]:
def play_multiple_times(env, policy, max_episodes):
    success = 0
    list_of_steps = []
    for i in range(max_episodes):
        total_reward, steps = play(env, policy)

        if total_reward > 0:
            success += 1
            list_of_steps.append(steps)

    print(f'Number of successes: {success}/{max_episodes}')
    print(f'Average number of steps: {np.mean(list_of_steps)}')

In [14]:
policy_0 = np.asarray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
play_multiple_times(env, policy_0, 1000)

Number of successes: 0/1000
Average number of steps: nan


/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


In [15]:
policy_1 = np.asarray([0, 1, 1, 3, 1, 0, 2, 0, 1, 1, 2, 2, 3, 3, 1, 0])
play_multiple_times(env, policy_1, 1000)

Number of successes: 57/1000
Average number of steps: 11.912280701754385


In [16]:
policy_2 = np.array([1, 1, 1, 3, 0, 1, 2, 3, 1, 1, 2, 3, 2, 2, 1, 3])
play_multiple_times(env, policy_2, 1000)

Number of successes: 90/1000
Average number of steps: 15.8


In [17]:
policy_3 = np.array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0])
play_multiple_times(env, policy_3, 1000)

Number of successes: 773/1000
Average number of steps: 45.377749029754206


# Policy Evaluation

In [18]:
def policy_evaluation(env, policy, max_iters=500, gamma=0.9):
    # Initialize the values of all states to be 0
    v_values = np.zeros(env.observation_space.n)
    for i in range(max_iters):
        prev_v_values = np.copy(v_values)

        # Update the value of each state
        for state in range(env.observation_space.n):
            action = policy[state]

            # Compute the q-value of the action
            q_value = 0
            for prob, next_state, reward, done in env.P[state][action]:
                q_value += prob * (reward + gamma * prev_v_values[next_state])

            v_values[state] = q_value # update v-value

        # Check convergence
        if np.all(np.isclose(v_values, prev_v_values)):
            print(f'Policy evaluation: Converged at {i}-th iteration.')
            break

    return v_values

In [19]:
policy_0 = np.asarray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
v_values_0 = policy_evaluation(env, policy_0)
print(v_values_0)

Policy evaluation: Converged at 0-th iteration.
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
policy_1 = np.asarray([0, 1, 1, 3, 1, 0, 2, 0, 1, 1, 2, 2, 3, 3, 1, 0])
v_values_1 = policy_evaluation(env, policy_1)
print(v_values_1)

Policy evaluation: Converged at 48-th iteration.
[0.01904157 0.01519815 0.03161906 0.02371389 0.02538879 0.
 0.06648515 0.         0.05924054 0.13822794 0.18999823 0.
 0.         0.21152109 0.56684236 0.        ]


In [21]:
np.all(v_values_1 >= v_values_0)

True

In [22]:
policy_2 = np.array([1, 1, 1, 3, 0, 1, 2, 3, 1, 1, 2, 3, 2, 2, 1, 3])
v_values_2 = policy_evaluation(env, policy_2)
print(v_values_2)

Policy evaluation: Converged at 53-th iteration.
[0.02889625 0.01951972 0.03616977 0.0271268  0.04790519 0.
 0.07391985 0.         0.08288277 0.19339319 0.21022995 0.
 0.         0.35153135 0.62684674 0.        ]


In [23]:
np.all(v_values_2 >= v_values_1)

True

In [24]:
policy_3 = np.array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0])
v_values_3 = policy_evaluation(env, policy_3)
print(v_values_3)

Policy evaluation: Converged at 80-th iteration.
[0.06888666 0.06141097 0.07440714 0.05580443 0.09185068 0.
 0.11220679 0.         0.14543323 0.24749485 0.29961611 0.
 0.         0.37993438 0.63901935 0.        ]


In [25]:
np.all(v_values_3 >= v_values_2)

True

# Value Iteration

In [26]:
def value_iteration(env, max_iters=500, gamma=0.9):
    # initialize
    v_values = np.zeros(env.observation_space.n)

    for i in range(max_iters):
        prev_v_values = np.copy(v_values)

        # update the v-value for each state
        for state in range(env.observation_space.n):
            q_values = []

            # compute the q-value for each action that we can perform at the state
            for action in range(env.action_space.n):
                q_value = 0
                # loop through each possible outcome
                for prob, next_state, reward, done in env.P[state][action]:
                    q_value += prob * (reward + gamma * prev_v_values[next_state])

                q_values.append(q_value)

            # select the max q-values
            best_action = np.argmax(q_values)
            v_values[state] = q_values[best_action]

        # check convergence
        if np.all(np.isclose(v_values, prev_v_values)):
            print(f'Value iteration: Converged at {i}-th iteration.')
            break

    return v_values

In [27]:
optimal_v_values = value_iteration(env, max_iters=500, gamma=0.9)

Value iteration: Converged at 79-th iteration.


In [28]:
optimal_v_values

array([0.06888615, 0.06141054, 0.07440682, 0.05580409, 0.09185022,
       0.        , 0.11220663, 0.        , 0.14543286, 0.2474946 ,
       0.29961593, 0.        , 0.        , 0.3799342 , 0.63901926,
       0.        ])

# Policy Extraction

In [29]:
def policy_extraction(env, v_values, gamma=0.9):
    # initialize
    policy = np.zeros(env.observation_space.n, dtype=np.int32)

    # loop through each state in the environment
    for state in range(env.observation_space.n):
        q_values = []
        # loop through each action
        for action in range(env.action_space.n):
            q_value = 0
            # loop each possible outcome
            for prob, next_state, reward, done in env.P[state][action]:
                q_value += prob * (reward + gamma * v_values[next_state])

            q_values.append(q_value)

        # select the best action
        best_action = np.argmax(q_values)
        policy[state] = best_action

    return policy

In [30]:
optimal_policy = policy_extraction(env, optimal_v_values, gamma=0.9)

In [31]:
optimal_policy

array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0], dtype=int32)

In [32]:
play(env, optimal_policy, True)

  (Down)
SFFF
FHFH
FFFH
HFFG



(1.0, 34)

In [33]:
play_multiple_times(env, optimal_policy, 1000)

Number of successes: 789/1000
Average number of steps: 41.447401774397974


# Policy Iteration

In [34]:
def policy_interation(env, max_iters=500, gamma=0.9):
    v_values = np.zeros(env.observation_space.n)
    currentPolicy = np.zeros(env.observation_space.n, dtype=np.int32)
    bestPolicy = []

    for i in range(max_iters):
        v_value = policy_evaluation(env, currentPolicy)
        nextPolicy = policy_extraction(env, v_value)
        if np.array_equal(nextPolicy, currentPolicy):
          bestPolicy = currentPolicy
          print(f'Policy iteration: Converged at {i}-th iteration.')
          break
        currentPolicy = nextPolicy
    return bestPolicy

# FrozenLake-v1

In [35]:
import time

valueTimes = []
policyTimes = []

In [36]:
FroLakv1 = gym.make('FrozenLake-v1', render_mode="ansi")

In [37]:
def timeCompute(env, type='value'):
  start, end = 0, 0
  if type == 'value':
    start = time.time()
    value = value_iteration(env)
    end = time.time()
    policy = policy_extraction(env, value, gamma=0.9)
  else:
    start = time.time()
    policy = policy_interation(env)
    end = time.time()
  return policy, end - start

In [38]:
FroLakv1_policy, timePolicy = timeCompute(FroLakv1, 'policy')
FroLakv1_value, timeValue = timeCompute(FroLakv1, 'value')

Policy evaluation: Converged at 0-th iteration.
Policy evaluation: Converged at 23-th iteration.
Policy evaluation: Converged at 59-th iteration.
Policy evaluation: Converged at 62-th iteration.
Policy evaluation: Converged at 79-th iteration.
Policy evaluation: Converged at 80-th iteration.
Policy iteration: Converged at 5-th iteration.
Value iteration: Converged at 79-th iteration.


In [39]:
print(f"Value Iteration: {timeValue} (s)")
print(f"Policy Iteration: {timePolicy} (s)")
valueTimes.append(timeValue)
policyTimes.append(timePolicy)

Value Iteration: 0.13229155540466309 (s)
Policy Iteration: 0.11452031135559082 (s)


In [40]:
play_multiple_times(FroLakv1, FroLakv1_policy, 1000)

Number of successes: 770/1000
Average number of steps: 40.44285714285714


# FrozenLake8x8-v1

In [41]:
FroLak8x8 = gym.make('FrozenLake-v1', map_name="8x8", render_mode="ansi")

In [42]:
FroLak8x8_policy, timePolicy = timeCompute(FroLak8x8, 'policy')
FroLak8x8_value, timeValue = timeCompute(FroLak8x8, 'value')

Policy evaluation: Converged at 27-th iteration.
Policy evaluation: Converged at 91-th iteration.
Policy evaluation: Converged at 92-th iteration.
Policy evaluation: Converged at 86-th iteration.
Policy evaluation: Converged at 90-th iteration.
Policy evaluation: Converged at 92-th iteration.
Policy evaluation: Converged at 95-th iteration.
Policy evaluation: Converged at 100-th iteration.
Policy evaluation: Converged at 112-th iteration.
Policy evaluation: Converged at 117-th iteration.
Policy iteration: Converged at 9-th iteration.
Value iteration: Converged at 117-th iteration.


In [43]:
print(f"Value Iteration: {timeValue} (s)")
print(f"Policy Iteration: {timePolicy} (s)")
valueTimes.append(timeValue)
policyTimes.append(timePolicy)

Value Iteration: 0.6320934295654297 (s)
Policy Iteration: 0.9953222274780273 (s)


In [44]:
play_multiple_times(FroLak8x8, FroLak8x8_policy, 1000)

Number of successes: 740/1000
Average number of steps: 74.2581081081081


# Taxi-v3

In [45]:
Taxiv3 = gym.make('Taxi-v3')

In [46]:
Taxiv3_policy, timePolicy = timeCompute(Taxiv3, 'policy')
Taxiv3_value, timeValue = timeCompute(Taxiv3, 'value')

Policy evaluation: Converged at 88-th iteration.
Policy evaluation: Converged at 97-th iteration.
Policy evaluation: Converged at 100-th iteration.
Policy evaluation: Converged at 101-th iteration.
Policy evaluation: Converged at 102-th iteration.
Policy evaluation: Converged at 103-th iteration.
Policy evaluation: Converged at 106-th iteration.
Policy evaluation: Converged at 109-th iteration.
Policy evaluation: Converged at 110-th iteration.
Policy evaluation: Converged at 111-th iteration.
Policy evaluation: Converged at 112-th iteration.
Policy evaluation: Converged at 115-th iteration.
Policy evaluation: Converged at 116-th iteration.
Policy evaluation: Converged at 116-th iteration.
Policy evaluation: Converged at 116-th iteration.
Policy evaluation: Converged at 116-th iteration.
Policy evaluation: Converged at 116-th iteration.
Policy iteration: Converged at 16-th iteration.
Value iteration: Converged at 116-th iteration.


In [47]:
print(f"Value Iteration: {timeValue} (s)")
print(f"Policy Iteration: {timePolicy} (s)")
valueTimes.append(timeValue)
policyTimes.append(timePolicy)

Value Iteration: 6.629977703094482 (s)
Policy Iteration: 15.605125427246094 (s)


In [48]:
play_multiple_times(Taxiv3, Taxiv3_policy, 1000)

Number of successes: 1000/1000
Average number of steps: 13.057


# Nhận xét

In [49]:
averageValue = np.average(valueTimes)
averagePolicy = np.average(policyTimes)

In [50]:
print(f"Giá trị thời gian trung bình của value iteration: {averageValue}")

Giá trị thời gian trung bình của value iteration: 2.464787562688192


In [51]:
print(f"Giá trị thời gian trung bình của value iteration: {averagePolicy}")

Giá trị thời gian trung bình của value iteration: 5.571655988693237


Dựa trên kết quả thực nghiệm, ta có thể thấy rằng thời gian chạy trung bình của value iteration thấp hơn so với policy iteration (2,4648 giây so với 5,5717 giây). Nguyên nhân chính là do policy iteration phải thực hiện đánh giá chiến lược (policy evaluation) và trích xuất chiến lược (policy extraction) liên tục với mỗi policy để dự đoán được chiến lược tiếp theo.

Tuy nhiên, mặc dù value iteration mất ít thời gian hơn để chạy, policy iteration luôn hội tụ nhanh hơn. Điều này là do mục tiêu cuối cùng của chúng ta vẫn là tìm kiếm chiến lược tối ưu, và policy iteration đánh giá chiến lược liên tục và sẽ trả về chiến lược tối ưu ngay khi nó được tìm thấy (khi *nextPolicy* trùng với *currentPolicy*). Trong khi đó, value iteration lại tìm chiến lược tối ưu dựa trên sự khác biệt cực nhỏ giữa V_values.

Do đó, mặc dù trong các bài toán trên, policy iteration có thể tốn chi phí tính toán cao hơn với việc đánh giá chiến lược liên tục, nhưng trong các bài toán lớn hơn, policy iteration có thể thể hiện hiệu suất tốt hơn vì khả năng hội tụ chiến lược tối ưu nhanh hơn. Điều này làm cho policy iteration trở thành lựa chọn thích hợp hơn cho các bài toán lớn, khi chúng ta đặt ưu tiên vào sự hội tụ nhanh chóng của thuật toán.

